// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAghWFUZLh4_oREd2EaskSloBymu471fF4',
    appId: '1:294000242910:web:93aa423d21e5fc115bd24f',
    messagingSenderId: '294000242910',
    projectId: 'myotplogin-42cb4',
    authDomain: 'myotplogin-42cb4.firebaseapp.com',
    storageBucket: 'myotplogin-42cb4.appspot.com',
    measurementId: 'G-ED0PD1140G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQuowGm3xOUe0Oa6M8vquqIhmjTBDnwRQ',
    appId: '1:294000242910:android:0453712ff769ec2b5bd24f',
    messagingSenderId: '294000242910',
    projectId: 'myotplogin-42cb4',
    storageBucket: 'myotplogin-42cb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIdCzww5CB5dfpUtPwZsSaxI00ws7jWiI',
    appId: '1:294000242910:ios:035d59e33fc69b8c5bd24f',
    messagingSenderId: '294000242910',
    projectId: 'myotplogin-42cb4',
    storageBucket: 'myotplogin-42cb4.appspot.com',
    iosBundleId: 'com.techease.loginWithOtp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIdCzww5CB5dfpUtPwZsSaxI00ws7jWiI',
    appId: '1:294000242910:ios:035d59e33fc69b8c5bd24f',
    messagingSenderId: '294000242910',
    projectId: 'myotplogin-42cb4',
    storageBucket: 'myotplogin-42cb4.appspot.com',
    iosBundleId: 'com.techease.loginWithOtp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAghWFUZLh4_oREd2EaskSloBymu471fF4',
    appId: '1:294000242910:web:96a7e71e64f059135bd24f',
    messagingSenderId: '294000242910',
    projectId: 'myotplogin-42cb4',
    authDomain: 'myotplogin-42cb4.firebaseapp.com',
    storageBucket: 'myotplogin-42cb4.appspot.com',
    measurementId: 'G-6RRHE1N5BD',
  );
}
